name: Python Code Tests

on:
  push:
    branches:
      - feature/python-code

permissions:
  contents: read
  pull-requests: write

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r app/requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest app/tests/

  create-pull-request:
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GIT_PAT }}
        run: |
          if gh pr list --base development --head feature/python-code --state open | grep -q "feature/python-code"; then
            echo "PR already exists, skipping creation."
          else
            gh pr create \
              --base development \
              --head feature/python-code \
              --title "Auto PR: Merge feature/python-code into development" \
              --body "This pull request was automatically created by GitHub Actions."
            echo "PR created successfully."
          fi
