name: Docker Build Check

on:
  push:
    branches:
      - feature/docker-configuration

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t test-image .
   create-pull-request:
   runs-on: ubuntu-latest
   needs: build-docker
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4 
     
     - name: Create Pull Request
       env:
         GH_TOKEN: ${{ secrets.GIT_PAT}}
       run: |
         if gh pr list --base development --head 'feature/*' --state open | grep -q "'feature/*'"; then
           echo "PR already exists, skipping creation."
         else
           gh pr create \
             --base development \
             --head 'feature/*' \
             --title "Auto PR: Merge 'feature/*' into development" \
             --body "This pull request was automatically created by Github Actions."
           echo "PR created successfully."
         fi
