name: Docker Build Check

on:
  push:
    branches:
      - 'feature/*'
  # pull_request:
    # types: ["opened","reopened"]
    # branches:
      # - 'feature/*'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
        continue-on-error: true

      - name: Dry run docker build process
        run: |
          docker build --progress=plain --no-cache -t test-image .
          
      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
  create-pull-request:
    needs: build-docker 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GIT_PAT }}
        run: |
          if gh pr list --base development --head feature/new --state open | grep -q "feature/new"; then
            echo "PR already exists, skipping creation." 
          else
            gh pr create \
              --base development \
              --head feature/new \
              --title "Auto PR: Merge feature/new into development" \
              --body "This pull request was automatically created by GitHub Action."
            echo "PR created successfully."
          fi
          
