name: Build and Push Docker Image

on:
  push:
    branches:
      
      - development
    tags:
      - 'v*.*.*'
  
  
  

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker build -t al0314/fastapi-sample-project-CI:$IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push al0314/fastapi-sample-project-CI:$IMAGE_TAG
